[package]
name = "cairo_playground"
version = "0.1.0"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest

[dependencies]
# foo = { path = "vendor/foo" }

[scripts]
lib = "../cairo/target/release/cairo-run --single-file src/lib.cairo"
hello = "../cairo/target/release/cairo-run --single-file src/hello.cairo"